project:
  name: "java-ai-review-showcase"

reviews:
  summarize_changes: true
  inline_suggestions: true
  style_guides:
    - google-java-style
  focus:
    - readability
    - maintainability
    - error-handling
    - naming

rules:
  max_method_length: 40
  avoid_magic_numbers: true
  avoid_catching_generic: true
  prefer_constructor_injection: true

exclude:
  - "**/target/**"
  - "**/build/**"
